import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProviders } from "@/components/shared/ReduxProviders";
import ToasterProvider from "@/components/shared/ToasterProvider";
import ClientDebugger from "@/components/ClientDebugger";
import DebugComponent from "@/components/DebugComponent";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body data-app="online-shop">
        <DebugComponent name="RootLayout" />
        <div id="app-root">
          <ReduxProviders>
            {children}
            <ToasterProvider />
            <ClientDebugger />
          </ReduxProviders>
        </div>
      </body>
    </html>
  );
}

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <Toaster />
//       </body>
//     </html>
//   );
// }
